import test from "node:test";
import assert from "node:assert/strict";
import { assessPullRequest, assessBranchHeads } from "../src/evidence/commission-gate.js";
const a="a".repeat(40), b="b".repeat(40);
const pr={number:12,state:"open",draft:false,changed_files:1,head:{sha:a},base:{sha:b,repo:{full_name:"ngl-damien/No-Gas-Labs-Alpha-1"}}};
const files=[{filename:"src/evidence/commission-gate.js",changes:42}];
const check={name:"world-projection",head_sha:a,status:"completed",conclusion:"success"};
const checks={total_count:1,check_runs:[check]};
const run=(p=pr,f=files,c=checks)=>assessPullRequest({pr:p,files:f,checks:c});
test("exact commit with code delta and passing CI is observed",()=>assert.equal(run().verdict,"CODE_AND_CI_OBSERVED"));
test("passing CI does not imply Founder approval",()=>assert.equal(run().limits.founder_approval,"NOT_ESTABLISHED"));
test("draft is not ready",()=>assert.ok(run({...pr,draft:true}).failures.includes("DRAFT_OR_UNKNOWN")));
test("no commit delta fails",()=>assert.ok(run({...pr,head:{sha:b}}).failures.includes("NO_COMMIT_DELTA")));
test("empty diff fails",()=>assert.ok(run({...pr,changed_files:0},[]).failures.includes("CHANGESET_NOT_CONFIRMED")));
test("documentation-only is not executable delta",()=>assert.ok(run(pr,[{filename:"docs/note.md",changes:20}]).failures.includes("NO_EXECUTABLE_SOURCE_OR_TEST_DELTA")));
test("queued check fails",()=>assert.ok(run(pr,files,{total_count:1,check_runs:[{...check,status:"queued"}]}).failures.includes("CHECK_NOT_SUCCESSFUL")));
test("check for wrong commit fails",()=>assert.ok(run(pr,files,{total_count:1,check_runs:[{...check,head_sha:b}]}).failures.includes("CHECK_SHA_MISMATCH")));
test("missing required workflow fails",()=>assert.ok(run(pr,files,{total_count:1,check_runs:[{...check,name:"other"}]}).failures.includes("REQUIRED_CHECK_MISSING:world-projection")));
test("incomplete pagination fails",()=>assert.ok(run(pr,files,{total_count:2,check_runs:[check]}).failures.includes("CHECKS_MISSING_OR_INCOMPLETE")));
test("empty experiment branch detected",()=>assert.equal(assessBranchHeads({base:{commit:{sha:a}},head:{commit:{sha:a}}}).verdict,"NO_DELTA"));
test("different heads are not sufficient",()=>assert.equal(assessBranchHeads({base:{commit:{sha:a}},head:{commit:{sha:b}}}).verdict,"UNREVIEWED_DELTA"));
