import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign } from "node:crypto";
import { establishGenesis } from "../src/authority/genesis.js";
import { decisionDigest } from "../src/authority/decision.js";
import { makeReceipt } from "../src/evidence/content-addressed.js";
import { projectWorld } from "../src/world/project.js";
import { defineQuest, projectQuest } from "../src/quest/engine.js";
const canonical=v=>Array.isArray(v)?"["+v.map(canonical).join(",")+"]":v&&typeof v==="object"?"{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+canonical(v[k])).join(",")+"}":JSON.stringify(v);
const {privateKey,publicKey}=generateKeyPairSync("ec",{namedCurve:"P-256"});
const genesis=establishGenesis({public_key_jwk:publicKey.export({format:"jwk"}),evidence_sha256:"a".repeat(64),challenge:"test only",founder_declaration:"I accept the inaugural No_Gas_Labs Founder key"});
const payload={schema:"ngl.founder-decision.v1",proposal_id:"p1",quest_id:"q1",capabilities:["world.progress"],outputs:[],acceptance:[],expires_at:"2099-01-01T00:00:00Z"};
const signed_decision={payload_sha256:decisionDigest(payload),key_fingerprint:genesis.key_fingerprint,signature:sign("sha256",Buffer.from(canonical(payload)),privateKey).toString("base64url")};
const bytes=Buffer.from("verified work");
const event={event_id:"e1",event_type:"SYSTEM_EVENT",subject:"q1",quest_id:"q1",grant_id:signed_decision.payload_sha256,required_capability:"world.progress",signed_decision,decision_payload:payload,admission:"ACCEPTED",authority:"AUTHORIZED",execution:"EXECUTED",evidence:"OBSERVED",outcome:"SUCCEEDED",receipts:[makeReceipt(bytes)],world_effect:{xp:10}};
const opts={genesis,now:0,resolveArtifact:()=>bytes};
test("unsigned authority text never awards XP",()=>assert.equal(projectWorld([{...event,signed_decision:undefined}],undefined,opts).xp,0));
test("signed grant with verified bytes awards XP",()=>assert.equal(projectWorld([event],undefined,opts).xp,10));
test("grant cannot be replayed under a different event id",()=>assert.equal(projectWorld([event,{...event,event_id:"e2"}],undefined,opts).xp,10));
test("tampered capability is rejected",()=>assert.equal(projectWorld([{...event,required_capability:"repository.admin"}],undefined,opts).xp,0));
test("expired decision is rejected",()=>assert.equal(projectWorld([event],undefined,{...opts,now:Date.parse("2100-01-01")}).xp,0));
test("unsigned revocation cannot suppress legitimate grant",()=>assert.equal(projectWorld([{event_id:"r1",event_type:"REVOCATION",revokes:event.grant_id},event],undefined,opts).xp,10));
test("quest rejects fabricated grant",()=>{const q=defineQuest({quest_id:"q1",title:"Test",objective:"Test",acceptance:["a"]});assert.equal(projectQuest(q,[{type:"QUEST_AUTHORIZED",grant_id:"fake",quest_id:"q1"}]).authorized,false)});
