import test from "node:test"; import assert from "node:assert/strict";
import {defineQuest,projectQuest,authorizeQuest,QUEST_STATUS} from "../src/quest/engine.js";
const quest=defineQuest({quest_id:"reconstitute-alpha-1",title:"Reconstitute Alpha-1",objective:"Make No_Gas_Labs progressively capable without inventing execution.",acceptance:["mesh-protocol","adversarial-tests"],capabilities:["repository.write","evidence.verify"]});
const auth=authorizeQuest({quest,grant_id:"g-alpha"});
const trusted = {authorize:e=>e.event_id===auth.event_id||e.event_type==="EXECUTION_ADJUDICATION"};
test("definition alone earns nothing",()=>assert.equal(projectQuest(quest).status,QUEST_STATUS.OPEN));
test("authorization is not completion",()=>assert.equal(projectQuest(quest,[auth],trusted).status,QUEST_STATUS.OPEN));
test("executor-shaped claim cannot complete quest",()=>assert.equal(projectQuest(quest,[auth,{quest_id:quest.quest_id,outcome:"SUCCEEDED",acceptance_satisfied:quest.acceptance}],trusted).status,QUEST_STATUS.AUTHORIZED));
test("partial accepted evidence remains in progress",()=>{const e={event_id:"e1",event_type:"EXECUTION_ADJUDICATION",subject:quest.quest_id,admission:"ACCEPTED",outcome:"SUCCEEDED",acceptance_satisfied:["mesh-protocol"]}; assert.equal(projectQuest(quest,[auth,e],trusted).status,QUEST_STATUS.OPEN);});
test("all acceptance conditions require accepted adjudications",()=>{const es=quest.acceptance.map((a,i)=>({event_id:`e${i}`,event_type:"EXECUTION_ADJUDICATION",subject:quest.quest_id,admission:"ACCEPTED",outcome:"SUCCEEDED",acceptance_satisfied:[a]})); assert.equal(projectQuest(quest,[auth,...es],trusted).status,QUEST_STATUS.OPEN);});
test("rejected evidence cannot satisfy acceptance",()=>{const e={event_id:"bad",event_type:"EXECUTION_ADJUDICATION",subject:quest.quest_id,admission:"REJECTED",outcome:"SUCCEEDED",acceptance_satisfied:quest.acceptance}; assert.equal(projectQuest(quest,[auth,e]).status,QUEST_STATUS.AUTHORIZED);});
